controllers/EtapaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Etapa;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EtapaController implements the CRUD actions for Etapa model.
 */
class EtapaController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Etapa models.
     *
     * @return string
     */
    public function actionIndex() {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            $dataProvider = new ActiveDataProvider([
                'query' => Etapa::find(),
                    /*
                      'pagination' => [
                      'pageSize' => 50
                      ],
                      'sort' => [
                      'defaultOrder' => [
                      'numetapa' => SORT_DESC,
                      ]
                      ],
                     */
            ]);

            return $this->render('index', [
                        'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * Displays a single Etapa model.
     * @param int $numetapa Numetapa
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($numetapa) {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('view', [
                        'model' => $this->findModel($numetapa),
            ]);
        }
    }

    /**
     * Creates a new Etapa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            $model = new Etapa();

            if ($this->request->isPost) {
                if ($model->load($this->request->post()) && $model->save()) {
                    return $this->redirect(['view', 'numetapa' => $model->numetapa]);
                }
            } else {
                $model->loadDefaultValues();
            }

            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Etapa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $numetapa Numetapa
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($numetapa) {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            $model = $this->findModel($numetapa);

            if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'numetapa' => $model->numetapa]);
            }

            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Etapa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $numetapa Numetapa
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($numetapa) {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            $this->findModel($numetapa)->delete();

            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the Etapa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $numetapa Numetapa
     * @return Etapa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($numetapa) {
        if (($model = Etapa::findOne(['numetapa' => $numetapa])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/LlevaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Lleva;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LlevaController implements the CRUD actions for Lleva model.
 */
class LlevaController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Lleva models.
     *
     * @return string
     */
    public function actionIndex() {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            $dataProvider = new ActiveDataProvider([
                'query' => Lleva::find(),
                    /*
                      'pagination' => [
                      'pageSize' => 50
                      ],
                      'sort' => [
                      'defaultOrder' => [
                      'numetapa' => SORT_DESC,
                      'código' => SORT_DESC,
                      ]
                      ],
                     */
            ]);

            return $this->render('index', [
                        'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * Displays a single Lleva model.
     * @param int $numetapa Numetapa
     * @param string $código Código
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($numetapa, $código) {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('view', [
                        'model' => $this->findModel($numetapa, $código),
            ]);
        }
    }

    /**
     * Creates a new Lleva model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            $model = new Lleva();

            if ($this->request->isPost) {
                if ($model->load($this->request->post()) && $model->save()) {
                    return $this->redirect(['view', 'numetapa' => $model->numetapa, 'código' => $model->código]);
                }
            } else {
                $model->loadDefaultValues();
            }

            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Lleva model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $numetapa Numetapa
     * @param string $código Código
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($numetapa, $código) {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            $model = $this->findModel($numetapa, $código);

            if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'numetapa' => $model->numetapa, 'código' => $model->código]);
            }

            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Lleva model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $numetapa Numetapa
     * @param string $código Código
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($numetapa, $código) {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            $this->findModel($numetapa, $código)->delete();

            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the Lleva model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $numetapa Numetapa
     * @param string $código Código
     * @return Lleva the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($numetapa, $código) {
        if (($model = Lleva::findOne(['numetapa' => $numetapa, 'código' => $código])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        if (Yii::$app->user->isGuest) {
            return $this->render('index');
        } else {
            return $this->render('crud');
        }
    }

    public function actionShame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('shame');
        }
    }

    public function actionCrud() {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('crud');
        }
    }

    public function actionCyclistfame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('cyclistfame');
        }
    }

    public function actionTeamfame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('teamfame');
        }
    }

    public function actionStagefame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('stagefame');
        }
    }

    public function actionMaillotfame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('maillotfame');
        }
    }

    public function actionCyclistshame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('cyclistshame');
        }
    }

    public function actionTeamshame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('teamshame');
        }
    }

    public function actionStageshame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('stageshame');
        }
    }

    public function actionMaillotshame() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return $this->render('maillotshame');
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
//    public function actionContact() {
//        $model = new ContactForm();
//        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
//            Yii::$app->session->setFlash('contactFormSubmitted');
//
//            return $this->refresh();
//        }
//        return $this->render('contact', [
//                    'model' => $model,
//        ]);
//    }

    /**
     * Displays about page.
     *
     * @return string
     */
//    public function actionAbout() {
//        return $this->render('about');
//    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/crud.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'MAD Awards 2022';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent text-white" Style="margin-bottom: 0px">
        <h1 class="display-4">CRUD MANAGEMENT</h1>

        <p class="lead">Here you can create, read, update or delete registers from the app</p>

    </div>

    <div class="body-content">

        <div class="card-deck flex-row">
            
            <div class="card center  fame-card">
                <?= Html::img("@web/images/A_cyclist.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Cyclists', ['ciclista/index'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
            <div class="card center  fame-card">
                <?= Html::img("@web/images/A_team.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Teams', ['equipo/index'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
            <div class="card center  fame-card">
                <?= Html::img("@web/images/A_stage.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Stages', ['etapa/index'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
            <div class="card center  fame-card">
                <?= Html::img("@web/images/A_maillot.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Maillots', ['maillot/index'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
                        <div class="card center  fame-card">
                <?= Html::img("@web/images/port.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Ports', ['puerto/index'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
                        <div class="card center  fame-card">
                <?= Html::img("@web/images/carries.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Carries', ['lleva/index'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
        </div>

    </div>
</div>

views/site/cyclistshame.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'WORST CYCLYSTS';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent text-white comic" Style="margin-bottom: -30px">
        <h1 class="display-4 comic">WORST CYCLYSTS CATEGORY AWARDS</h1>

        <p class="lead">Hard work has a future payoff. Laziness pays off now.</p>
        
    </div>

    <div class="body-content">

        <div class="card-deck flex-row">

            <div class="card text-center  shame-card">
                <?= Html::img("@web/images/B_stages.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Least stages won Award</h5>
                    <?= Html::a('View', ['ciclista/lsw'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

            <div class="card text-center  shame-card">
                <?= Html::img("@web/images/maillot_grayed.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Least maillots won Award</h5>
                    <?= Html::a('View', ['lleva/lmw'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

            <div class="card text-center  shame-card">
                <?= Html::img("@web/images/B_port.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Least ports won Award</h5>
                    <?= Html::a('View', ['port/lpw'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

        </div>

        <div class="jumbotron text-right bg-transparent text-white d-flex col-12" Style="justify-content: space-between; padding-bottom: 1px; margin-bottom: 0px ">
            <?= Html::a('Print dossier', ['site/print'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Go back', ['site/shame'], ['class' => 'btn btn-danger']) ?>
        </div>

    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'MAD Awards 2022';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent text-white" Style="margin-bottom: 0px">
        <h1 class="display-4">HALL OF FAME</h1>

        <p class="lead">Where everyone wants to be, but just a few are willing to do anything to get there.</p>

    </div>

    <div class="body-content">

        <div class="card-deck flex-row">
            
            <div class="card center  fame-card">
                <?= Html::img("@web/images/A_cyclist.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Cyclists', ['site/cyclistfame'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
            <div class="card center  fame-card">
                <?= Html::img("@web/images/A_team.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Teams', ['site/teamfame'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
            <div class="card center  fame-card">
                <?= Html::img("@web/images/A_stage.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Stages', ['site/stagefame'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
            <div class="card center  fame-card">
                <?= Html::img("@web/images/A_maillot.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Maillots', ['site/maillotfame'], ['class' => 'btn btn-warning']) ?>
                </div>
            </div>
            
        </div>

        <div class="jumbotron text-right bg-transparent text-white flex-shrink-1" Style="padding-bottom: 1px; margin-bottom: 0px">
            <?= Html::a('Now available the long-awaited... Hall of Shame', ['site/shame'], ['class' => 'text-reset lead']) ?>
        </div>

    </div>
</div>

views/site/maillotshame.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'EASYEST MAILLOTS';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent text-white comic" Style="margin-bottom: -30px">
        <h1 class="display-4 comic">EASYEST MAILLOTS CATEGORY AWARDS</h1>

        <p class="lead">All I ask is the chance to prove that money can't make me happy.</p>

    </div>

    <div class="body-content">

        <div class="card-deck flex-row" Style="justify-content: space-around">

            <div class="card text-center  shame-card col-4">
                <?= Html::img("@web/images/maillots.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Most given maillot Award</h5>
                    <?= Html::a('View', ['lleva/mgm'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

            <div class="card text-center  shame-card col-4">
                <?= Html::img("@web/images/B_maillot.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Less valued maillot Award</h5>
                    <?= Html::a('View', ['maillot/lva'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

        </div>

        <div class="jumbotron text-right bg-transparent text-white d-flex col-12" Style="justify-content: space-between; padding-bottom: 1px; margin-bottom: 0px ">
            <?= Html::a('Print dossier', ['site/print'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Go back', ['site/shame'], ['class' => 'btn btn-danger']) ?>
        </div>

    </div>
</div>

views/site/shame.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'MAD Awards 2022';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent text-white comic" Style="margin-bottom: 0px">
        <h1 class="display-4 comic">HALL OF SHAME</h1>

        <p class="lead">Errors have been made. Others will be blamed.</p>

    </div>

    <div class="body-content">

        <div class="card-deck flex-row">
            
            <div class="card center  shame-card">
                <?= Html::img("@web/images/B_cyclist.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Cyclists', ['site/cyclistshame'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>
            
            <div class="card center  shame-card">
                <?= Html::img("@web/images/B_team.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Teams', ['site/teamshame'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>
            
            <div class="card center  shame-card">
                <?= Html::img("@web/images/B_stage.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Stages', ['site/stageshame'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>
            
            <div class="card center  shame-card">
                <?= Html::img("@web/images/B_maillot.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <?= Html::a('Maillots', ['site/maillotshame'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>
            
        </div>

        <div class="jumbotron text-right bg-transparent text-white flex-shrink-1" Style="padding-bottom: 1px; margin-bottom: 0px">
            <?= Html::a('Take me back to the Hall of Fame..', ['site/index'], ['class' => 'text-reset lead']) ?>
        </div>

    </div>
</div>

views/site/stageshame.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'WEIRD STAGES';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent text-white comic" Style="margin-bottom: -30px">
        <h1 class="display-4 comic">WEIRD STAGES CATEGORY AWARDS</h1>

        <p class="lead">Ever stop to think, and forget to start again?</p>

    </div>

    <div class="body-content">

        <div class="card-deck flex-row">

            <div class="card text-center  shame-card">
                <?= Html::img("@web/images/B_stage.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Shortest stage Award</h5>
                    <?= Html::a('View', ['etapa/ssa'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

            <div class="card text-center  shame-card">
                <?= Html::img("@web/images/B_port.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Least ports Award</h5>
                    <?= Html::a('View', ['puerto/lpa'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

            <div class="card text-center  shame-card">
                <?= Html::img("@web/images/small_port.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Smallest port Award</h5>
                    <?= Html::a('View', ['puerto/spa'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

        </div>

        <div class="jumbotron text-right bg-transparent text-white d-flex col-12" Style="justify-content: space-between; padding-bottom: 1px; margin-bottom: 0px ">
            <?= Html::a('Print dossier', ['site/print'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Go back', ['site/shame'], ['class' => 'btn btn-danger']) ?>
        </div>

    </div>
</div>

views/site/teamshame.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'WORST TEAMS';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent text-white comic" Style="margin-bottom: -30px">
        <h1 class="display-4 comic">WORST TEAMS CATEGORY AWARDS</h1>

        <p class="lead">Teamwork is essential, it allows you to blame someone else.</p>

    </div>

    <div class="body-content">

        <div class="card-deck flex-row" Style="justify-content: space-around">

            <div class="card text-center  shame-card col-4">
                <?= Html::img("@web/images/B_stages.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Least stages won Award</h5>
                    <?= Html::a('View', ['equipo/lsw'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

            <div class="card text-center  shame-card col-4">
                <?= Html::img("@web/images/w_director.png", ['class' => 'resize']) ?>
                <div class="card-body">
                    <h5 class="card-title">Worst director Award</h5>
                    <?= Html::a('View', ['equipo/wda'], ['class' => 'btn btn-danger']) ?>
                </div>
            </div>

        </div>

        <div class="jumbotron text-right bg-transparent text-white d-flex col-12" Style="justify-content: space-between; padding-bottom: 1px; margin-bottom: 0px ">
            <?= Html::a('Print dossier', ['site/print'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Go back', ['site/shame'], ['class' => 'btn btn-danger']) ?>
        </div>

    </div>
</div>